# Generated by Django 3.2.10 on 2021-12-30 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.SlugField(default=secrets.token_urlsafe)),
                ('allow_new_signups', models.BooleanField(default=True, help_text='Indicates whether new users can create a new account when signing up.')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(choices=[('en', 'English')], default='en', help_text='An ISO 639 language code (with optional variant) selected by the user. Ex: en-GB.', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SIGNED_IN', 'Signed in')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('original_extension', models.CharField(max_length=64)),
                ('unique', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('is_image', models.BooleanField(default=False)),
                ('image_width', models.PositiveSmallIntegerField(null=True)),
                ('image_height', models.PositiveSmallIntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
